version: 1
type: maven
resolver:
  snapshotRepo: virual-maven
  releaseRepo: virual-maven
  serverID: artifactory
deployer:
  snapshotRepo: local-maven
  releaseRepo: local-maven
  serverID: artifactory
