version: 1
type: maven
resolver:
  snapshotRepo: virtual-maven
  releaseRepo: virtual-maven
  serverID: artifactory
deployer:
  snapshotRepo: local-maven
  releaseRepo: local-maven
  serverID: artifactory
