version: 1
type: maven
resolver:
  snapshotRepo: ${VIRTUAL_REPO}
  releaseRepo: ${VIRTUAL_REPO}
  serverID: ${ARTIFACTORY_ID}
deployer:
  snapshotRepo: ${LOCAL_REPO}
  releaseRepo: ${LOCAL_REPO}
  serverID: ${ARTIFACTORY_ID}
